#vich_uploader:
 #   db_driver: orm

# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '/images/products'
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\OrignameNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
